language: elixir
elixir:
  - 1.7
  - 1.8
otp_release:
  - 21.0
sudo: false

before_install:
- sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
- sudo apt-get update -qq
- sudo apt-get install -q -y libavcodec-dev libavformat-dev libavutil-dev

script:
  - mix format --check-formatted
  - mix test
